# Config del sitio
title:              Agustín Covarrubias
bio:
  es:               'Un estudiante apasionado por la informática y la ciencia.'
  en:               'A student passionate about computing and science.'
description:        "Un estudiante apasionado por la informática y la biomedicina. Blog y web personal."
reading_time:       true
words_per_minute:   200

logo:               'assets/img/logo3.png'
background:         'https://source.unsplash.com/daily/'
locale:             es_ES
url:                https://agucova.me
tiled_bg: false

# Jekyll
enforce_ssl:        agucova.me
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   agucova

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-50420608-9
  verify:           MOLr9EOxX0OuegrLMQxSOhzZHnImzWo0A-h3I1nhOP8
  #ad-client:
  #ad-slot:
#bing-verify:
email:              agustin@agucova.me
twitter:            austinc3301
github-url:             agucova
stackoverflow:      4595150/forgotten-player-agucova
#linkedin:           username
#xing:              username
instagram:          agustin_covarrubias
# lastfm:             agucova
#tumblr:             username
#pinterest:         username
#foursquare:        username
#steam:              agucova
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
keybase:           agucova
#xmpp:              username@server.com
#hackernews:        username

# Gems
analytics :
  provider : google
  google :
      tracking_id : 'UA-50420608-6'
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Translations
languages: ["es", "en"]
default_lang: "es"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
